version: "3.9"

services:
  script:
    build: .
    command: python main.py
    volumes:
      - .:/statbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}